title: Alauda Build of Gitlab Docs
logoText: Alauda Build of Gitlab Docs
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
    - docs/shared/crds/*.yml
  openapis:
    - docs/shared/openapis/**/*.json
    - docs/shared/openapis/**/*.yaml
    - docs/shared/openapis/**/*.yml
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
internalRoutes:
  - '**/development/**/*'

releaseNotes:
  queryTemplates:
    ## TODO: change the versionMatch for the next releases
    unfixed: |
      project = <%= project %> AND affectedVersion in ("gitlab-ce-operator-<%= version %>") AND type = Bug AND status in (Cancelled) AND ReleaseNotesStatus = Publish

    fixed: |
      project = <%= project %> AND fixVersion in ("gitlab-ce-operator-<%= version %>") AND type = Bug AND status in (Done, Resolved) AND ReleaseNotesStatus = Publish

editRepoBaseUrl: alauda/gitlab-docs

translate:
  # 系统提示语，ejs 模板，传入的参数有 `sourceLang`, `targetLang`, `additionalPrompts`
  # 其中 `sourceLang` 和 `targetLang` 是 `中文` 和 `英文` 两个字符串，
  #     `additionalPrompts` 为 `i18n` 中的 `additionalPrompts` 配置，可能为空
  userPrompt: |
    - Please keep the following terms untranslated
      * ACP
      * Alauda support for PostgreSQL
      * Alauda Cache Service for Redis OSS
      * Alauda Build of Gitlab
      * Administrator
      * Marketplace
      * Operator Hub
